// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CancelOrganizationSubscriptionEndpointHandlerData,
  CancelOrganizationSubscriptionEndpointHandlerResponses,
  CreateOrganizationEndpointHandlerData,
  CreateOrganizationEndpointHandlerResponses,
  CreateOrganizationSubscriptionEndpointHandlerData,
  CreateOrganizationSubscriptionEndpointHandlerResponses,
  DemoteUserEndpointHandlerData,
  DemoteUserEndpointHandlerErrors,
  DemoteUserEndpointHandlerResponses,
  GetCurrentUserEndpointHandlerData,
  GetCurrentUserEndpointHandlerErrors,
  GetCurrentUserEndpointHandlerResponses,
  GetCurrentUserSessionsEndpointHandlerData,
  GetCurrentUserSessionsEndpointHandlerErrors,
  GetCurrentUserSessionsEndpointHandlerResponses,
  GetOrganizationByIdEndpointHandlerData,
  GetOrganizationByIdEndpointHandlerResponses,
  GetOrganizationMembersEndpointHandlerData,
  GetOrganizationMembersEndpointHandlerResponses,
  GetOrganizationsEndpointHandlerData,
  GetOrganizationsEndpointHandlerResponses,
  GetOrganizationSubscriptionEndpointHandlerData,
  GetOrganizationSubscriptionEndpointHandlerResponses,
  GetUserByIdEndpointHandlerData,
  GetUserByIdEndpointHandlerErrors,
  GetUserByIdEndpointHandlerResponses,
  GetUsersEndpointHandlerData,
  GetUsersEndpointHandlerErrors,
  GetUsersEndpointHandlerResponses,
  InviteOrganizationMemberEndpointHandlerData,
  InviteOrganizationMemberEndpointHandlerResponses,
  LockUserEndpointHandlerData,
  LockUserEndpointHandlerErrors,
  LockUserEndpointHandlerResponses,
  LoginUserEndpointHandlerData,
  LoginUserEndpointHandlerErrors,
  LoginUserEndpointHandlerResponses,
  LogoutUserEndpointHandlerData,
  LogoutUserEndpointHandlerErrors,
  LogoutUserEndpointHandlerResponses,
  PromoteUserEndpointHandlerData,
  PromoteUserEndpointHandlerErrors,
  PromoteUserEndpointHandlerResponses,
  RefreshSessionEndpointHandlerData,
  RefreshSessionEndpointHandlerErrors,
  RefreshSessionEndpointHandlerResponses,
  RegisterUserEndpointHandlerData,
  RegisterUserEndpointHandlerErrors,
  RegisterUserEndpointHandlerResponses,
  RevokeAllCurrentUserSessionsEndpointHandlerData,
  RevokeAllCurrentUserSessionsEndpointHandlerErrors,
  RevokeAllCurrentUserSessionsEndpointHandlerResponses,
  RevokeCurrentUserSessionEndpointHandlerData,
  RevokeCurrentUserSessionEndpointHandlerErrors,
  RevokeCurrentUserSessionEndpointHandlerResponses,
  UnlockUserEndpointHandlerData,
  UnlockUserEndpointHandlerErrors,
  UnlockUserEndpointHandlerResponses,
  UpdateCurrentUserEndpointHandlerData,
  UpdateCurrentUserEndpointHandlerErrors,
  UpdateCurrentUserEndpointHandlerResponses,
  UpdateCurrentUserPasswordEndpointHandlerData,
  UpdateCurrentUserPasswordEndpointHandlerErrors,
  UpdateCurrentUserPasswordEndpointHandlerResponses,
  UpdateOrganizationMemberRoleEndpointHandlerData,
  UpdateOrganizationMemberRoleEndpointHandlerResponses,
  UpdateOrganizationSubscriptionEndpointHandlerData,
  UpdateOrganizationSubscriptionEndpointHandlerResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Register a new user
 *
 * Registers a new user with the provided details:
 *
 * - `UserName`: Desired username (trimmed).
 * - `Email`: User's email (hashed internally).
 * - `Password`: User's password (hashed internally).
 * - `FirstName`, `MiddleName`, `LastName`: Personal names (encrypted).
 *
 * On success, the `Location` header contains the URI of the new user.
 *
 * Possible responses:
 * - `201 Created`: User successfully registered.
 * - `400 BadRequest`: Invalid or missing input.
 * - `409 Conflict`: Email already in use.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const registerUserEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegisterUserEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterUserEndpointHandlerResponses,
    RegisterUserEndpointHandlerErrors,
    ThrowOnError
  >({
    url: "/api/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Login a user
 *
 * Logs in a user and creates a new session:
 *
 * - `Identifier`: Email or username.
 * - `Password`: User's password.
 * - `RememberMe`: Optional; if true, session lasts 7 days, otherwise 8 hours.
 *
 * On success, a secure HTTP-only cookie `edu_session_id` is set to manage the session.
 *
 * Possible responses:
 * - `200 OK`: Login successful.
 * - `400 BadRequest`: Invalid input.
 * - `401 Unauthorized`: Incorrect credentials or account locked.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const loginUserEndpointHandler = <ThrowOnError extends boolean = false>(
  options: Options<LoginUserEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginUserEndpointHandlerResponses,
    LoginUserEndpointHandlerErrors,
    ThrowOnError
  >({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh user session
 *
 * Refreshes the current user session, extending its expiration
 * **only if the session is within the allowed refresh threshold**.
 *
 * **Authentication Required**: A valid session is needed.
 *
 * On success, a new secure HTTP-only `edu_session_id` cookie is set with updated timestamps.
 *
 * Possible responses:
 * - `200 OK`: Session successfully refreshed.
 * - `401 Unauthorized`: No valid session, session expired, or not eligible for refresh yet.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const refreshSessionEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RefreshSessionEndpointHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshSessionEndpointHandlerResponses,
    RefreshSessionEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/auth/refresh", ...options });

/**
 * Logout user
 *
 * Logs out the current user by revoking their session.
 *
 * **Authentication Required**: A valid session is needed.
 *
 * This endpoint performs the following actions:
 * - Revokes the current session in the database.
 * - Deletes the `edu_session_id` cookie from the client.
 *
 * Possible responses:
 * - `200 OK`: Successfully logged out.
 * - `401 Unauthorized`: No valid session (user may already be logged out).
 * - `500 InternalServerError`: Unexpected server error.
 */
export const logoutUserEndpointHandler = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutUserEndpointHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    LogoutUserEndpointHandlerResponses,
    LogoutUserEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/auth/logout", ...options });

/**
 * Get current user sessions
 *
 * Retrieves the current user's active sessions.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) is needed.
 *
 * **Notes**:
 * - Revoked sessions are not included in the response.
 *
 * Possible responses:
 * - `200 OK`: Sessions retrieved successfully.
 * - `401 Unauthorized`: No valid session or session expired.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const getCurrentUserSessionsEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCurrentUserSessionsEndpointHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCurrentUserSessionsEndpointHandlerResponses,
    GetCurrentUserSessionsEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/sessions/me", ...options });

/**
 * Revoke a current user specific session
 *
 * Revokes a specific session belonging to the current user.
 *
 * **Authentication Required**: A valid session is needed.
 *
 * **Route Parameter**:
 * - `id` (GUID): The ID of the session to revoke.
 *
 * **Behavior**:
 * - The specified session will be invalidated in the database.
 * - If the revoked session is the current session, the user may be logged out.
 * - No other sessions are affected.
 *
 * **Possible responses**:
 * - `200 OK`: Session successfully revoked.
 * - `404 NotFound`: Session ID does not exist or does not belong to the user.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const revokeCurrentUserSessionEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RevokeCurrentUserSessionEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RevokeCurrentUserSessionEndpointHandlerResponses,
    RevokeCurrentUserSessionEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/sessions/{id}/revoke", ...options });

/**
 * Revoke all current user sessions
 *
 * Revokes all sessions for the current user **except the current one**.
 *
 * **Authentication Required**: A valid session is needed.
 *
 * **Query Parameter**:
 * - `keepCurrentUserSession` (bool, optional): If `true`, the current session will be preserved; default is `false`.
 *
 * **Behavior**:
 * - All sessions except the one specified (or current session if `keepCurrentUserSession = true`) are revoked.
 * - Any revoked session will be logged out automatically.
 *
 * **Possible responses**:
 * - `200 OK`: All targeted sessions successfully revoked.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const revokeAllCurrentUserSessionsEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    RevokeAllCurrentUserSessionsEndpointHandlerData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).post<
    RevokeAllCurrentUserSessionsEndpointHandlerResponses,
    RevokeAllCurrentUserSessionsEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/sessions/revoke-all", ...options });

/**
 * Get users (cursor pagination)
 *
 * Retrieves users using cursor-based pagination.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) and **Admin or SuperAdmin role** are required.
 *
 * **Query Parameters**:
 * - `cursor` (GUID, optional): Fetch users after this cursor (exclusive).
 * - `limit` (int, optional): Page size (default 20, max 100).
 * - `id` (GUID, optional): Filter by a specific user ID.
 * - `userName` (string, optional): Filter by username (partial match).
 *
 * The response includes:
 * - `Items`: Users for the current page.
 * - `NextCursor`: Cursor value for the next page (if any).
 * - `HasMore`: Indicates whether more users are available.
 *
 * Possible responses:
 * - `200 OK`: Users retrieved successfully.
 * - `403 Forbidden`: Current user does not have Admin or SuperAdmin privileges.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const getUsersEndpointHandler = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersEndpointHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetUsersEndpointHandlerResponses,
    GetUsersEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/users", ...options });

/**
 * Get current authenticated user
 *
 * Retrieves the profile of the currently authenticated user.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) is needed.
 *
 * The response includes:
 * - `Id`: User's unique identifier.
 * - `UserName`: Display username.
 * - `FirstName`, `MiddleName`, `LastName`: Personal names.
 * - `Role`: User's system role (e.g., Admin, User).
 *
 * Possible responses:
 * - `200 OK`: User profile successfully retrieved.
 * - `401 Unauthorized`: No valid session or session expired.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const getCurrentUserEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCurrentUserEndpointHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCurrentUserEndpointHandlerResponses,
    GetCurrentUserEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/users/me", ...options });

/**
 * Update current user profile
 *
 * Updates the profile of the currently authenticated user.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) is needed.
 *
 * **Request Body**:
 * - `UserName` (string, optional): New display username.
 * - `FirstName` (string, optional): Updated first name.
 * - `MiddleName` (string, optional): Updated middle name.
 * - `LastName` (string, optional): Updated last name.
 * - `Email` (string, optional): Updated email address.
 * - `Password` (string, optional): New password (must meet complexity rules).
 *
 * **Notes**:
 * - Fields not included in the request body will remain unchanged.
 * - Attempting to set a username or email that already exists will result in a conflict.
 *
 * **Possible responses**:
 * - `200 OK`: Profile updated successfully.
 * - `400 BadRequest`: Invalid input or failed validation (e.g., invalid email format).
 * - `409 Conflict`: Username or email already in use.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const updateCurrentUserEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCurrentUserEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateCurrentUserEndpointHandlerResponses,
    UpdateCurrentUserEndpointHandlerErrors,
    ThrowOnError
  >({
    url: "/api/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get user by ID
 *
 * Retrieves the public profile of a user by their unique ID.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) is needed.
 *
 * **Route Parameters**:
 * - `id` (GUID): The unique identifier of the user to retrieve.
 *
 * The response includes:
 * - `Id`: User's unique identifier.
 * - `UserName`: Display username.
 * - `FirstName`, `MiddleName`, `LastName`: Personal names.
 * - `Role`: User's system role.
 *
 * Possible responses:
 * - `200 OK`: User profile successfully retrieved.
 * - `401 Unauthorized`: No valid session or session expired.
 * - `404 NotFound`: No user exists with the specified ID.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const getUserByIdEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserByIdEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUserByIdEndpointHandlerResponses,
    GetUserByIdEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/users/{id}", ...options });

/**
 * Update current user password
 *
 * Updates the password for the currently authenticated user.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) is needed.
 *
 * **Request Body**:
 * - `CurrentPassword` (string, required): The user's current password.
 * - `NewPassword` (string, required): New password (must meet complexity rules).
 * - `LogoutAll` (boolean, optional): If true, also revoke the current session (full logout).
 *
 * **Notes**:
 * - Other active sessions will be revoked after a successful password change.
 * - When `LogoutAll` is false (default), the current session remains active.
 *
 * **Possible responses**:
 * - `200 OK`: Password updated successfully.
 * - `400 BadRequest`: Invalid input or failed validation (e.g., password complexity).
 * - `401 Unauthorized`: Invalid session or current password is incorrect.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const updateCurrentUserPasswordEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCurrentUserPasswordEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateCurrentUserPasswordEndpointHandlerResponses,
    UpdateCurrentUserPasswordEndpointHandlerErrors,
    ThrowOnError
  >({
    url: "/api/users/me/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Promote user
 *
 * Promotes a user to the next role in the system hierarchy.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) and **SuperAdmin role** are required.
 *
 * **Request Body**:
 * - `UserId` (GUID, required): The unique identifier of the user to promote.
 *
 * **Role Hierarchy**:
 * - User → Admin → SuperAdmin
 * - Users already at the highest role (SuperAdmin) cannot be promoted.
 *
 * **Notes**:
 * - Only SuperAdmins can perform this action.
 * - Attempting to promote a non-existent user will return `404 NotFound`.
 * - Attempting to promote a user already at the highest role will return `409 Conflict`.
 *
 * **Possible responses**:
 * - `200 OK`: User successfully promoted.
 * - `403 Forbidden`: Current user does not have SuperAdmin privileges.
 * - `404 NotFound`: No user exists with the specified ID.
 * - `409 Conflict`: User is already at the highest role.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const promoteUserEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PromoteUserEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PromoteUserEndpointHandlerResponses,
    PromoteUserEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/users/{id}/promote", ...options });

/**
 * Demote user
 *
 * Demotes a user to the previous role in the system hierarchy.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) and **SuperAdmin role** are required.
 *
 * **Request Body**:
 * - `UserId` (GUID, required): The unique identifier of the user to demote.
 *
 * **Role Hierarchy**:
 * - SuperAdmin → Admin → User
 * - Users already at the lowest role (User) cannot be demoted.
 *
 * **Notes**:
 * - Only SuperAdmins can perform this action.
 * - Attempting to demote a non-existent user will return `404 NotFound`.
 * - Attempting to demote a user already at the lowest role will return `409 Conflict`.
 *
 * **Possible responses**:
 * - `200 OK`: User successfully demoted.
 * - `403 Forbidden`: Current user does not have SuperAdmin privileges.
 * - `404 NotFound`: No user exists with the specified ID.
 * - `409 Conflict`: User is already at the lowest role.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const demoteUserEndpointHandler = <ThrowOnError extends boolean = false>(
  options: Options<DemoteUserEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DemoteUserEndpointHandlerResponses,
    DemoteUserEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/users/{id}/demote", ...options });

/**
 * Lock user account
 *
 * Locks a user account and revokes all active sessions, preventing the user from logging in until unlocked.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) and **Admin or SuperAdmin role** are required.
 *
 * **Request Body**:
 * - `UserId` (GUID, required): The unique identifier of the user account to lock.
 *
 * **Notes**:
 * - Locked users cannot access the system until an Admin or SuperAdmin unlocks their account.
 * - Attempting to lock a non-existent user will return `404 NotFound`.
 * - Users who are already locked will still return `200 OK` (idempotent operation).
 *
 * **Possible responses**:
 * - `200 OK`: User account successfully locked.
 * - `403 Forbidden`: Current user does not have Admin or SuperAdmin privileges.
 * - `404 NotFound`: No user exists with the specified ID.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const lockUserEndpointHandler = <ThrowOnError extends boolean = false>(
  options: Options<LockUserEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LockUserEndpointHandlerResponses,
    LockUserEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/users/{id}/lock", ...options });

/**
 * Unlock user account
 *
 * Unlocks a previously locked user account, allowing the user to log in again.
 *
 * **Authentication Required**: A valid session (`edu_session_id` cookie) and **Admin or SuperAdmin role** are required.
 *
 * **Request Body**:
 * - `UserId` (GUID, required): The unique identifier of the user account to unlock.
 *
 * **Notes**:
 * - Unlocking a user who is not currently locked will still return `200 OK` (idempotent operation).
 * - Attempting to unlock a non-existent user will return `404 NotFound`.
 *
 * **Possible responses**:
 * - `200 OK`: User account successfully unlocked.
 * - `403 Forbidden`: Current user does not have Admin or SuperAdmin privileges.
 * - `404 NotFound`: No user exists with the specified ID.
 * - `500 InternalServerError`: Unexpected server error.
 */
export const unlockUserEndpointHandler = <ThrowOnError extends boolean = false>(
  options: Options<UnlockUserEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UnlockUserEndpointHandlerResponses,
    UnlockUserEndpointHandlerErrors,
    ThrowOnError
  >({ url: "/api/users/{id}/unlock", ...options });

/**
 * List organizations
 */
export const getOrganizationsEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetOrganizationsEndpointHandlerData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetOrganizationsEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/organizations", ...options });

/**
 * Create organization
 */
export const createOrganizationEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateOrganizationEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateOrganizationEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/organizations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get organization by id
 */
export const getOrganizationByIdEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOrganizationByIdEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOrganizationByIdEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/organizations/{id}", ...options });

/**
 * Invite organization member
 */
export const inviteOrganizationMemberEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<InviteOrganizationMemberEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    InviteOrganizationMemberEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/organizations/{id}/invite",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update organization member role
 */
export const updateOrganizationMemberRoleEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateOrganizationMemberRoleEndpointHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateOrganizationMemberRoleEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/organizations/{id}/members/{memberId}/role",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get organization members
 */
export const getOrganizationMembersEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOrganizationMembersEndpointHandlerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOrganizationMembersEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/organizations/{id}/members", ...options });

/**
 * Get organization subscription
 */
export const getOrganizationSubscriptionEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetOrganizationSubscriptionEndpointHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetOrganizationSubscriptionEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/organizations/{id}/subscription", ...options });

/**
 * Update organization subscription
 */
export const updateOrganizationSubscriptionEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateOrganizationSubscriptionEndpointHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateOrganizationSubscriptionEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/organizations/{id}/subscription",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create organization subscription
 */
export const createOrganizationSubscriptionEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateOrganizationSubscriptionEndpointHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    CreateOrganizationSubscriptionEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/organizations/{id}/subscription",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Cancel organization subscription
 */
export const cancelOrganizationSubscriptionEndpointHandler = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CancelOrganizationSubscriptionEndpointHandlerData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    CancelOrganizationSubscriptionEndpointHandlerResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/organizations/{id}/subscription/cancel", ...options });
