// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3187" | (string & {});
};

export type ApiResponseOfCursorPageOfUserResponse = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: null | CursorPageOfUserResponse;
};

export type ApiResponseOfIReadOnlyListOfOrganizationListItemResponse = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: null | Array<OrganizationListItemResponse>;
};

export type ApiResponseOfIReadOnlyListOfOrganizationMemberResponse = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: null | Array<OrganizationMemberResponse>;
};

export type ApiResponseOfIReadOnlyListOfSessionData = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: null | Array<SessionData>;
};

export type ApiResponseOfObject = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: unknown;
};

export type ApiResponseOfOrganizationResponse = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: null | OrganizationResponse;
};

export type ApiResponseOfOrganizationSubscriptionResponse = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: null | OrganizationSubscriptionResponse;
};

export type ApiResponseOfSessionTimestampsResponse = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: null | SessionTimestampsResponse;
};

export type ApiResponseOfUserResponse = {
  success: boolean;
  messageId: string;
  message: string;
  details: null | Array<ResponseDetail>;
  data: null | UserResponse;
};

export type CreateOrganizationRequest = {
  name: string;
};

export type CreateOrganizationSubscriptionRequest = {
  planId: string;
  startsAt: string;
  endsAt: null | string;
  autoRenew: boolean;
};

export type CursorPageOfUserResponse = {
  items: Array<UserResponse>;
  nextCursor: null | string;
  hasMore: boolean;
};

export type InviteOrganizationMemberRequest = {
  userId: string;
  role: OrganizationMemberRole;
};

export type LoginUserRequest = {
  identifier: string;
  password: string;
  rememberMe?: boolean;
};

export type OrganizationListItemResponse = {
  organizationId: string;
  name: string;
  role: OrganizationMemberRole;
  status: OrganizationMemberStatus;
};

export type OrganizationMemberResponse = {
  id: string;
  userId: string;
  role: OrganizationMemberRole;
  status: OrganizationMemberStatus;
  joinedAt: string;
};

export type OrganizationMemberRole = "Member" | "Moderator" | "Owner";

export type OrganizationMemberStatus =
  | "Pending"
  | "Active"
  | "Suspended"
  | "Inactive"
  | "Banned";

export type OrganizationResponse = {
  id: string;
  name: string;
  ownerUserId: string;
  createdAt: string;
};

export type OrganizationSubscriptionResponse = {
  id: string;
  organizationId: string;
  planId: string;
  startsAt: string;
  endsAt: null | string;
  autoRenew: boolean;
  cancelledAt: null | string;
  isActive: boolean;
  isExpired: boolean;
  isCancelled: boolean;
};

export type RegisterUserCommand = {
  firstName: string;
  middleName: null | string;
  lastName: string;
  userName: string;
  email: string;
  password: string;
};

export type ResponseDetail = {
  message: string;
  severity: ResponseSeverity;
};

export type ResponseSeverity =
  | "Info"
  | "Partial"
  | "Warning"
  | "Error"
  | "Fatal";

export type SessionData = {
  sessionId: string;
  userId: string;
  createdAt: string;
  expiresAt: string;
  absoluteExpiresAt: string;
  isRevoked: boolean;
  rememberMe: boolean;
};

export type SessionTimestampsResponse = {
  expiresAt: string;
  absoluteExpiresAt: string;
};

export type UpdateCurrentUserPasswordRequest = {
  currentPassword: string;
  newPassword: string;
  logoutAll?: boolean;
};

export type UpdateCurrentUserRequest = {
  firstName: null | string;
  middleName: null | string;
  lastName: null | string;
  userName: null | string;
};

export type UpdateOrganizationMemberRoleRequest = {
  role: OrganizationMemberRole;
};

export type UpdateOrganizationSubscriptionRequest = {
  planId: null | string;
  startsAt: null | string;
  endsAt: null | string;
  autoRenew: null | boolean;
};

export type UserResponse = {
  id: string;
  userName: string;
  firstName: string;
  middleName: null | string;
  lastName: string;
  role: UserRole;
};

export type UserRole = "User" | "Admin" | "SuperAdmin";

export type RegisterUserEndpointHandlerData = {
  body: RegisterUserCommand;
  path?: never;
  query?: never;
  url: "/api/auth/register";
};

export type RegisterUserEndpointHandlerErrors = {
  /**
   * Bad Request
   */
  400: ApiResponseOfObject;
  /**
   * Conflict
   */
  409: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type RegisterUserEndpointHandlerError =
  RegisterUserEndpointHandlerErrors[keyof RegisterUserEndpointHandlerErrors];

export type RegisterUserEndpointHandlerResponses = {
  /**
   * Created
   */
  201: ApiResponseOfObject;
};

export type RegisterUserEndpointHandlerResponse =
  RegisterUserEndpointHandlerResponses[keyof RegisterUserEndpointHandlerResponses];

export type LoginUserEndpointHandlerData = {
  body: LoginUserRequest;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type LoginUserEndpointHandlerErrors = {
  /**
   * Bad Request
   */
  400: ApiResponseOfObject;
  /**
   * Unauthorized
   */
  401: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type LoginUserEndpointHandlerError =
  LoginUserEndpointHandlerErrors[keyof LoginUserEndpointHandlerErrors];

export type LoginUserEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfSessionTimestampsResponse;
};

export type LoginUserEndpointHandlerResponse =
  LoginUserEndpointHandlerResponses[keyof LoginUserEndpointHandlerResponses];

export type RefreshSessionEndpointHandlerData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/refresh";
};

export type RefreshSessionEndpointHandlerErrors = {
  /**
   * Unauthorized
   */
  401: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type RefreshSessionEndpointHandlerError =
  RefreshSessionEndpointHandlerErrors[keyof RefreshSessionEndpointHandlerErrors];

export type RefreshSessionEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfSessionTimestampsResponse;
};

export type RefreshSessionEndpointHandlerResponse =
  RefreshSessionEndpointHandlerResponses[keyof RefreshSessionEndpointHandlerResponses];

export type LogoutUserEndpointHandlerData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/logout";
};

export type LogoutUserEndpointHandlerErrors = {
  /**
   * Unauthorized
   */
  401: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type LogoutUserEndpointHandlerError =
  LogoutUserEndpointHandlerErrors[keyof LogoutUserEndpointHandlerErrors];

export type LogoutUserEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type LogoutUserEndpointHandlerResponse =
  LogoutUserEndpointHandlerResponses[keyof LogoutUserEndpointHandlerResponses];

export type GetCurrentUserSessionsEndpointHandlerData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/sessions/me";
};

export type GetCurrentUserSessionsEndpointHandlerErrors = {
  /**
   * Unauthorized
   */
  401: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type GetCurrentUserSessionsEndpointHandlerError =
  GetCurrentUserSessionsEndpointHandlerErrors[keyof GetCurrentUserSessionsEndpointHandlerErrors];

export type GetCurrentUserSessionsEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfIReadOnlyListOfSessionData;
};

export type GetCurrentUserSessionsEndpointHandlerResponse =
  GetCurrentUserSessionsEndpointHandlerResponses[keyof GetCurrentUserSessionsEndpointHandlerResponses];

export type RevokeCurrentUserSessionEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/sessions/{id}/revoke";
};

export type RevokeCurrentUserSessionEndpointHandlerErrors = {
  /**
   * Not Found
   */
  404: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type RevokeCurrentUserSessionEndpointHandlerError =
  RevokeCurrentUserSessionEndpointHandlerErrors[keyof RevokeCurrentUserSessionEndpointHandlerErrors];

export type RevokeCurrentUserSessionEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type RevokeCurrentUserSessionEndpointHandlerResponse =
  RevokeCurrentUserSessionEndpointHandlerResponses[keyof RevokeCurrentUserSessionEndpointHandlerResponses];

export type RevokeAllCurrentUserSessionsEndpointHandlerData = {
  body?: never;
  path?: never;
  query?: {
    keepCurrentUserSession?: boolean;
  };
  url: "/api/sessions/revoke-all";
};

export type RevokeAllCurrentUserSessionsEndpointHandlerErrors = {
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type RevokeAllCurrentUserSessionsEndpointHandlerError =
  RevokeAllCurrentUserSessionsEndpointHandlerErrors[keyof RevokeAllCurrentUserSessionsEndpointHandlerErrors];

export type RevokeAllCurrentUserSessionsEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type RevokeAllCurrentUserSessionsEndpointHandlerResponse =
  RevokeAllCurrentUserSessionsEndpointHandlerResponses[keyof RevokeAllCurrentUserSessionsEndpointHandlerResponses];

export type GetUsersEndpointHandlerData = {
  body?: never;
  path?: never;
  query?: {
    cursor?: string;
    limit?: number | string;
    id?: string;
    userName?: string;
  };
  url: "/api/users";
};

export type GetUsersEndpointHandlerErrors = {
  /**
   * Forbidden
   */
  403: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type GetUsersEndpointHandlerError =
  GetUsersEndpointHandlerErrors[keyof GetUsersEndpointHandlerErrors];

export type GetUsersEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfCursorPageOfUserResponse;
};

export type GetUsersEndpointHandlerResponse =
  GetUsersEndpointHandlerResponses[keyof GetUsersEndpointHandlerResponses];

export type GetCurrentUserEndpointHandlerData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/me";
};

export type GetCurrentUserEndpointHandlerErrors = {
  /**
   * Unauthorized
   */
  401: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type GetCurrentUserEndpointHandlerError =
  GetCurrentUserEndpointHandlerErrors[keyof GetCurrentUserEndpointHandlerErrors];

export type GetCurrentUserEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfUserResponse;
};

export type GetCurrentUserEndpointHandlerResponse =
  GetCurrentUserEndpointHandlerResponses[keyof GetCurrentUserEndpointHandlerResponses];

export type UpdateCurrentUserEndpointHandlerData = {
  body: UpdateCurrentUserRequest;
  path?: never;
  query?: never;
  url: "/api/users/me";
};

export type UpdateCurrentUserEndpointHandlerErrors = {
  /**
   * Bad Request
   */
  400: ApiResponseOfObject;
  /**
   * Conflict
   */
  409: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type UpdateCurrentUserEndpointHandlerError =
  UpdateCurrentUserEndpointHandlerErrors[keyof UpdateCurrentUserEndpointHandlerErrors];

export type UpdateCurrentUserEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type UpdateCurrentUserEndpointHandlerResponse =
  UpdateCurrentUserEndpointHandlerResponses[keyof UpdateCurrentUserEndpointHandlerResponses];

export type GetUserByIdEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type GetUserByIdEndpointHandlerErrors = {
  /**
   * Unauthorized
   */
  401: ApiResponseOfObject;
  /**
   * Not Found
   */
  404: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type GetUserByIdEndpointHandlerError =
  GetUserByIdEndpointHandlerErrors[keyof GetUserByIdEndpointHandlerErrors];

export type GetUserByIdEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfUserResponse;
};

export type GetUserByIdEndpointHandlerResponse =
  GetUserByIdEndpointHandlerResponses[keyof GetUserByIdEndpointHandlerResponses];

export type UpdateCurrentUserPasswordEndpointHandlerData = {
  body: UpdateCurrentUserPasswordRequest;
  path?: never;
  query?: never;
  url: "/api/users/me/password";
};

export type UpdateCurrentUserPasswordEndpointHandlerErrors = {
  /**
   * Bad Request
   */
  400: ApiResponseOfObject;
  /**
   * Unauthorized
   */
  401: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type UpdateCurrentUserPasswordEndpointHandlerError =
  UpdateCurrentUserPasswordEndpointHandlerErrors[keyof UpdateCurrentUserPasswordEndpointHandlerErrors];

export type UpdateCurrentUserPasswordEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type UpdateCurrentUserPasswordEndpointHandlerResponse =
  UpdateCurrentUserPasswordEndpointHandlerResponses[keyof UpdateCurrentUserPasswordEndpointHandlerResponses];

export type PromoteUserEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}/promote";
};

export type PromoteUserEndpointHandlerErrors = {
  /**
   * Forbidden
   */
  403: ApiResponseOfObject;
  /**
   * Not Found
   */
  404: ApiResponseOfObject;
  /**
   * Conflict
   */
  409: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type PromoteUserEndpointHandlerError =
  PromoteUserEndpointHandlerErrors[keyof PromoteUserEndpointHandlerErrors];

export type PromoteUserEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type PromoteUserEndpointHandlerResponse =
  PromoteUserEndpointHandlerResponses[keyof PromoteUserEndpointHandlerResponses];

export type DemoteUserEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}/demote";
};

export type DemoteUserEndpointHandlerErrors = {
  /**
   * Forbidden
   */
  403: ApiResponseOfObject;
  /**
   * Not Found
   */
  404: ApiResponseOfObject;
  /**
   * Conflict
   */
  409: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type DemoteUserEndpointHandlerError =
  DemoteUserEndpointHandlerErrors[keyof DemoteUserEndpointHandlerErrors];

export type DemoteUserEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type DemoteUserEndpointHandlerResponse =
  DemoteUserEndpointHandlerResponses[keyof DemoteUserEndpointHandlerResponses];

export type LockUserEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}/lock";
};

export type LockUserEndpointHandlerErrors = {
  /**
   * Forbidden
   */
  403: ApiResponseOfObject;
  /**
   * Not Found
   */
  404: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type LockUserEndpointHandlerError =
  LockUserEndpointHandlerErrors[keyof LockUserEndpointHandlerErrors];

export type LockUserEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type LockUserEndpointHandlerResponse =
  LockUserEndpointHandlerResponses[keyof LockUserEndpointHandlerResponses];

export type UnlockUserEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}/unlock";
};

export type UnlockUserEndpointHandlerErrors = {
  /**
   * Forbidden
   */
  403: ApiResponseOfObject;
  /**
   * Not Found
   */
  404: ApiResponseOfObject;
  /**
   * Internal Server Error
   */
  500: ApiResponseOfObject;
};

export type UnlockUserEndpointHandlerError =
  UnlockUserEndpointHandlerErrors[keyof UnlockUserEndpointHandlerErrors];

export type UnlockUserEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type UnlockUserEndpointHandlerResponse =
  UnlockUserEndpointHandlerResponses[keyof UnlockUserEndpointHandlerResponses];

export type GetOrganizationsEndpointHandlerData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/organizations";
};

export type GetOrganizationsEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfIReadOnlyListOfOrganizationListItemResponse;
};

export type GetOrganizationsEndpointHandlerResponse =
  GetOrganizationsEndpointHandlerResponses[keyof GetOrganizationsEndpointHandlerResponses];

export type CreateOrganizationEndpointHandlerData = {
  body: CreateOrganizationRequest;
  path?: never;
  query?: never;
  url: "/api/organizations";
};

export type CreateOrganizationEndpointHandlerResponses = {
  /**
   * Created
   */
  201: ApiResponseOfObject;
};

export type CreateOrganizationEndpointHandlerResponse =
  CreateOrganizationEndpointHandlerResponses[keyof CreateOrganizationEndpointHandlerResponses];

export type GetOrganizationByIdEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/organizations/{id}";
};

export type GetOrganizationByIdEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfOrganizationResponse;
};

export type GetOrganizationByIdEndpointHandlerResponse =
  GetOrganizationByIdEndpointHandlerResponses[keyof GetOrganizationByIdEndpointHandlerResponses];

export type InviteOrganizationMemberEndpointHandlerData = {
  body: InviteOrganizationMemberRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/organizations/{id}/invite";
};

export type InviteOrganizationMemberEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type InviteOrganizationMemberEndpointHandlerResponse =
  InviteOrganizationMemberEndpointHandlerResponses[keyof InviteOrganizationMemberEndpointHandlerResponses];

export type UpdateOrganizationMemberRoleEndpointHandlerData = {
  body: UpdateOrganizationMemberRoleRequest;
  path: {
    id: string;
    memberId: string;
  };
  query?: never;
  url: "/api/organizations/{id}/members/{memberId}/role";
};

export type UpdateOrganizationMemberRoleEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type UpdateOrganizationMemberRoleEndpointHandlerResponse =
  UpdateOrganizationMemberRoleEndpointHandlerResponses[keyof UpdateOrganizationMemberRoleEndpointHandlerResponses];

export type GetOrganizationMembersEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/organizations/{id}/members";
};

export type GetOrganizationMembersEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfIReadOnlyListOfOrganizationMemberResponse;
};

export type GetOrganizationMembersEndpointHandlerResponse =
  GetOrganizationMembersEndpointHandlerResponses[keyof GetOrganizationMembersEndpointHandlerResponses];

export type GetOrganizationSubscriptionEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/organizations/{id}/subscription";
};

export type GetOrganizationSubscriptionEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfOrganizationSubscriptionResponse;
};

export type GetOrganizationSubscriptionEndpointHandlerResponse =
  GetOrganizationSubscriptionEndpointHandlerResponses[keyof GetOrganizationSubscriptionEndpointHandlerResponses];

export type UpdateOrganizationSubscriptionEndpointHandlerData = {
  body: UpdateOrganizationSubscriptionRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/organizations/{id}/subscription";
};

export type UpdateOrganizationSubscriptionEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type UpdateOrganizationSubscriptionEndpointHandlerResponse =
  UpdateOrganizationSubscriptionEndpointHandlerResponses[keyof UpdateOrganizationSubscriptionEndpointHandlerResponses];

export type CreateOrganizationSubscriptionEndpointHandlerData = {
  body: CreateOrganizationSubscriptionRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/organizations/{id}/subscription";
};

export type CreateOrganizationSubscriptionEndpointHandlerResponses = {
  /**
   * Created
   */
  201: ApiResponseOfObject;
};

export type CreateOrganizationSubscriptionEndpointHandlerResponse =
  CreateOrganizationSubscriptionEndpointHandlerResponses[keyof CreateOrganizationSubscriptionEndpointHandlerResponses];

export type CancelOrganizationSubscriptionEndpointHandlerData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/organizations/{id}/subscription/cancel";
};

export type CancelOrganizationSubscriptionEndpointHandlerResponses = {
  /**
   * OK
   */
  200: ApiResponseOfObject;
};

export type CancelOrganizationSubscriptionEndpointHandlerResponse =
  CancelOrganizationSubscriptionEndpointHandlerResponses[keyof CancelOrganizationSubscriptionEndpointHandlerResponses];
