// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3187' | (string & {});
};

export type ApiResponseOfCourseResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | CourseResponse;
};

export type ApiResponseOfCursorPageOfUserResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | CursorPageOfUserResponse;
};

export type ApiResponseOfGuid = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: string;
};

export type ApiResponseOfIReadOnlyListOfCourseOfferingResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<CourseOfferingResponse>;
};

export type ApiResponseOfIReadOnlyListOfCourseResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<CourseResponse>;
};

export type ApiResponseOfIReadOnlyListOfOrganizationInviteResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<OrganizationInviteResponse>;
};

export type ApiResponseOfIReadOnlyListOfOrganizationListItemResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<OrganizationListItemResponse>;
};

export type ApiResponseOfIReadOnlyListOfOrganizationMemberResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<OrganizationMemberResponse>;
};

export type ApiResponseOfIReadOnlyListOfSemesterResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<SemesterResponse>;
};

export type ApiResponseOfIReadOnlyListOfSessionData = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<SessionData>;
};

export type ApiResponseOfIReadOnlyListOfTermResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<TermResponse>;
};

export type ApiResponseOfIReadOnlyListOfUserOrganizationInviteResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | Array<UserOrganizationInviteResponse>;
};

export type ApiResponseOfObject = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: unknown;
};

export type ApiResponseOfOrganizationResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | OrganizationResponse;
};

export type ApiResponseOfSemesterResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | SemesterResponse;
};

export type ApiResponseOfSessionTimestampsResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | SessionTimestampsResponse;
};

export type ApiResponseOfTermResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | TermResponse;
};

export type ApiResponseOfUserResponse = {
    success: boolean;
    messageId: string;
    message: string;
    details: null | Array<ResponseDetail>;
    data: null | UserResponse;
};

export type CourseOfferingResponse = {
    id: string;
    courseId: string;
    courseName: string;
    courseCode: string;
    semesterId: string;
    termId: string;
    termOrdinal: number | string;
    semesterStartYear: number | string;
    organizationId: string;
    createdAt: string;
    semesterEndYear?: number | string;
    session?: null | string;
};

export type CourseResponse = {
    id: string;
    name: string;
    code: string;
    organizationId: string;
    createdAt: string;
};

export type CreateCourseOfferingRequest = {
    organizationId: string;
    courseId: string;
    termId: string;
};

export type CreateCourseRequest = {
    organizationId: string;
    name: string;
    code: string;
};

export type CreateOrganizationRequest = {
    name: string;
};

export type CreateSemesterRequest = {
    organizationId: string;
    startYear: number | string;
};

export type CreateTermRequest = {
    organizationId: string;
    semesterId: string;
    ordinal: number | string;
};

export type CursorPageOfUserResponse = {
    items: Array<UserResponse>;
    nextCursor: null | string;
    hasMore: boolean;
};

export type InviteOrganizationMemberRequest = {
    userId?: string | null;
    userName?: string | null;
};

export type LoginUserRequest = {
    identifier: string;
    password: string;
    rememberMe?: boolean;
};

export type OrganizationInviteResponse = {
    id: string;
    organizationId: string;
    organizationName: string;
    invitedUserId: string;
    invitedByUserId: string;
    status: OrganizationInviteStatus;
    expiresAt: string;
    createdAt: string;
};

export type OrganizationInviteStatus = 'Pending' | 'Accepted' | 'Rejected' | 'Cancelled' | 'Expired';

export type OrganizationListItemResponse = {
    organizationId: string;
    name: string;
    role: OrganizationMemberRole;
    status: OrganizationMemberStatus;
};

export type OrganizationMemberResponse = {
    id: string;
    userId: string;
    userName: string;
    firstName: string;
    lastName: string;
    role: OrganizationMemberRole;
    status: OrganizationMemberStatus;
    joinedAt: string;
};

export type OrganizationMemberRole = 'Member' | 'Moderator' | 'Owner';

export type OrganizationMemberStatus = 'Active' | 'Inactive' | 'Banned';

export type OrganizationResponse = {
    id: string;
    name: string;
    ownerUserId: string;
    createdAt: string;
};

export type RegisterUserCommand = {
    firstName: string;
    middleName: null | string;
    lastName: string;
    userName: string;
    email: string;
    password: string;
};

export type ResponseDetail = {
    message: string;
    severity: ResponseSeverity;
};

export type ResponseSeverity = 'Info' | 'Partial' | 'Warning' | 'Error' | 'Fatal';

export type SemesterResponse = {
    id: string;
    startYear: number | string;
    organizationId: string;
    createdAt: string;
    endYear?: number | string;
    session?: null | string;
};

export type SessionData = {
    sessionId: string;
    userId: string;
    createdAt: string;
    expiresAt: string;
    absoluteExpiresAt: string;
    isRevoked: boolean;
    rememberMe: boolean;
};

export type SessionTimestampsResponse = {
    expiresAt: string;
    absoluteExpiresAt: string;
};

export type TermResponse = {
    id: string;
    semesterId: string;
    ordinal: number | string;
    semesterStartYear: number | string;
    organizationId: string;
    createdAt: string;
    semesterEndYear?: number | string;
    session?: null | string;
};

export type TransferOrganizationOwnershipRequest = {
    memberId: string;
};

export type UpdateCourseRequest = {
    organizationId: string;
    name: string;
    code: string;
};

export type UpdateCurrentUserPasswordRequest = {
    currentPassword: string;
    newPassword: string;
    logoutAll?: boolean;
};

export type UpdateCurrentUserRequest = {
    firstName: null | string;
    middleName: null | string;
    lastName: null | string;
    userName: null | string;
};

export type UpdateOrganizationMemberRoleRequest = {
    role: OrganizationMemberRole;
};

export type UpdateOrganizationRequest = {
    name: string;
};

export type UserOrganizationInviteResponse = {
    id: string;
    organizationId: string;
    organizationName: string;
    invitedByUserName: string;
    expiresAt: string;
    createdAt: string;
};

export type UserResponse = {
    id: string;
    userName: string;
    firstName: string;
    middleName: null | string;
    lastName: string;
    role: UserRole;
};

export type UserRole = 'User' | 'Admin' | 'SuperAdmin';

export type RegisterUserEndpointHandlerData = {
    body: RegisterUserCommand;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterUserEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type RegisterUserEndpointHandlerError = RegisterUserEndpointHandlerErrors[keyof RegisterUserEndpointHandlerErrors];

export type RegisterUserEndpointHandlerResponses = {
    /**
     * Created
     */
    201: ApiResponseOfObject;
};

export type RegisterUserEndpointHandlerResponse = RegisterUserEndpointHandlerResponses[keyof RegisterUserEndpointHandlerResponses];

export type LoginUserEndpointHandlerData = {
    body: LoginUserRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginUserEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type LoginUserEndpointHandlerError = LoginUserEndpointHandlerErrors[keyof LoginUserEndpointHandlerErrors];

export type LoginUserEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfSessionTimestampsResponse;
};

export type LoginUserEndpointHandlerResponse = LoginUserEndpointHandlerResponses[keyof LoginUserEndpointHandlerResponses];

export type RefreshSessionEndpointHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshSessionEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type RefreshSessionEndpointHandlerError = RefreshSessionEndpointHandlerErrors[keyof RefreshSessionEndpointHandlerErrors];

export type RefreshSessionEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfSessionTimestampsResponse;
};

export type RefreshSessionEndpointHandlerResponse = RefreshSessionEndpointHandlerResponses[keyof RefreshSessionEndpointHandlerResponses];

export type LogoutUserEndpointHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutUserEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type LogoutUserEndpointHandlerError = LogoutUserEndpointHandlerErrors[keyof LogoutUserEndpointHandlerErrors];

export type LogoutUserEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type LogoutUserEndpointHandlerResponse = LogoutUserEndpointHandlerResponses[keyof LogoutUserEndpointHandlerResponses];

export type GetCoursesEndpointHandlerData = {
    body?: never;
    path?: never;
    query: {
        organizationId: string;
    };
    url: '/api/courses';
};

export type GetCoursesEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
};

export type GetCoursesEndpointHandlerError = GetCoursesEndpointHandlerErrors[keyof GetCoursesEndpointHandlerErrors];

export type GetCoursesEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfCourseResponse;
};

export type GetCoursesEndpointHandlerResponse = GetCoursesEndpointHandlerResponses[keyof GetCoursesEndpointHandlerResponses];

export type CreateCourseEndpointHandlerData = {
    body: CreateCourseRequest;
    path?: never;
    query?: never;
    url: '/api/courses';
};

export type CreateCourseEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
};

export type CreateCourseEndpointHandlerError = CreateCourseEndpointHandlerErrors[keyof CreateCourseEndpointHandlerErrors];

export type CreateCourseEndpointHandlerResponses = {
    /**
     * Created
     */
    201: ApiResponseOfGuid;
};

export type CreateCourseEndpointHandlerResponse = CreateCourseEndpointHandlerResponses[keyof CreateCourseEndpointHandlerResponses];

export type DeleteCourseEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/courses/{id}';
};

export type DeleteCourseEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type DeleteCourseEndpointHandlerError = DeleteCourseEndpointHandlerErrors[keyof DeleteCourseEndpointHandlerErrors];

export type DeleteCourseEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type DeleteCourseEndpointHandlerResponse = DeleteCourseEndpointHandlerResponses[keyof DeleteCourseEndpointHandlerResponses];

export type GetCourseByIdEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/courses/{id}';
};

export type GetCourseByIdEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type GetCourseByIdEndpointHandlerError = GetCourseByIdEndpointHandlerErrors[keyof GetCourseByIdEndpointHandlerErrors];

export type GetCourseByIdEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfCourseResponse;
};

export type GetCourseByIdEndpointHandlerResponse = GetCourseByIdEndpointHandlerResponses[keyof GetCourseByIdEndpointHandlerResponses];

export type UpdateCourseEndpointHandlerData = {
    body: UpdateCourseRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/courses/{id}';
};

export type UpdateCourseEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
};

export type UpdateCourseEndpointHandlerError = UpdateCourseEndpointHandlerErrors[keyof UpdateCourseEndpointHandlerErrors];

export type UpdateCourseEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type UpdateCourseEndpointHandlerResponse = UpdateCourseEndpointHandlerResponses[keyof UpdateCourseEndpointHandlerResponses];

export type CreateCourseOfferingEndpointHandlerData = {
    body: CreateCourseOfferingRequest;
    path?: never;
    query?: never;
    url: '/api/course-offerings';
};

export type CreateCourseOfferingEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
};

export type CreateCourseOfferingEndpointHandlerError = CreateCourseOfferingEndpointHandlerErrors[keyof CreateCourseOfferingEndpointHandlerErrors];

export type CreateCourseOfferingEndpointHandlerResponses = {
    /**
     * Created
     */
    201: ApiResponseOfGuid;
};

export type CreateCourseOfferingEndpointHandlerResponse = CreateCourseOfferingEndpointHandlerResponses[keyof CreateCourseOfferingEndpointHandlerResponses];

export type GetCourseOfferingsBySemesterEndpointHandlerData = {
    body?: never;
    path: {
        semesterId: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/course-offerings/semester/{semesterId}';
};

export type GetCourseOfferingsBySemesterEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type GetCourseOfferingsBySemesterEndpointHandlerError = GetCourseOfferingsBySemesterEndpointHandlerErrors[keyof GetCourseOfferingsBySemesterEndpointHandlerErrors];

export type GetCourseOfferingsBySemesterEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfCourseOfferingResponse;
};

export type GetCourseOfferingsBySemesterEndpointHandlerResponse = GetCourseOfferingsBySemesterEndpointHandlerResponses[keyof GetCourseOfferingsBySemesterEndpointHandlerResponses];

export type DeleteCourseOfferingEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/course-offerings/{id}';
};

export type DeleteCourseOfferingEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type DeleteCourseOfferingEndpointHandlerError = DeleteCourseOfferingEndpointHandlerErrors[keyof DeleteCourseOfferingEndpointHandlerErrors];

export type DeleteCourseOfferingEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type DeleteCourseOfferingEndpointHandlerResponse = DeleteCourseOfferingEndpointHandlerResponses[keyof DeleteCourseOfferingEndpointHandlerResponses];

export type GetOrganizationsEndpointHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations';
};

export type GetOrganizationsEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetOrganizationsEndpointHandlerError = GetOrganizationsEndpointHandlerErrors[keyof GetOrganizationsEndpointHandlerErrors];

export type GetOrganizationsEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfOrganizationListItemResponse;
};

export type GetOrganizationsEndpointHandlerResponse = GetOrganizationsEndpointHandlerResponses[keyof GetOrganizationsEndpointHandlerResponses];

export type CreateOrganizationEndpointHandlerData = {
    body: CreateOrganizationRequest;
    path?: never;
    query?: never;
    url: '/api/organizations';
};

export type CreateOrganizationEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type CreateOrganizationEndpointHandlerError = CreateOrganizationEndpointHandlerErrors[keyof CreateOrganizationEndpointHandlerErrors];

export type CreateOrganizationEndpointHandlerResponses = {
    /**
     * Created
     */
    201: ApiResponseOfObject;
};

export type CreateOrganizationEndpointHandlerResponse = CreateOrganizationEndpointHandlerResponses[keyof CreateOrganizationEndpointHandlerResponses];

export type DeleteOrganizationEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/organizations/{id}';
};

export type DeleteOrganizationEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type DeleteOrganizationEndpointHandlerError = DeleteOrganizationEndpointHandlerErrors[keyof DeleteOrganizationEndpointHandlerErrors];

export type DeleteOrganizationEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type DeleteOrganizationEndpointHandlerResponse = DeleteOrganizationEndpointHandlerResponses[keyof DeleteOrganizationEndpointHandlerResponses];

export type GetOrganizationByIdEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/organizations/{id}';
};

export type GetOrganizationByIdEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetOrganizationByIdEndpointHandlerError = GetOrganizationByIdEndpointHandlerErrors[keyof GetOrganizationByIdEndpointHandlerErrors];

export type GetOrganizationByIdEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfOrganizationResponse;
};

export type GetOrganizationByIdEndpointHandlerResponse = GetOrganizationByIdEndpointHandlerResponses[keyof GetOrganizationByIdEndpointHandlerResponses];

export type UpdateOrganizationEndpointHandlerData = {
    body: UpdateOrganizationRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/organizations/{id}';
};

export type UpdateOrganizationEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type UpdateOrganizationEndpointHandlerError = UpdateOrganizationEndpointHandlerErrors[keyof UpdateOrganizationEndpointHandlerErrors];

export type UpdateOrganizationEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type UpdateOrganizationEndpointHandlerResponse = UpdateOrganizationEndpointHandlerResponses[keyof UpdateOrganizationEndpointHandlerResponses];

export type GetOrganizationInvitesEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/organizations/{id}/invites';
};

export type GetOrganizationInvitesEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetOrganizationInvitesEndpointHandlerError = GetOrganizationInvitesEndpointHandlerErrors[keyof GetOrganizationInvitesEndpointHandlerErrors];

export type GetOrganizationInvitesEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfOrganizationInviteResponse;
};

export type GetOrganizationInvitesEndpointHandlerResponse = GetOrganizationInvitesEndpointHandlerResponses[keyof GetOrganizationInvitesEndpointHandlerResponses];

export type InviteOrganizationMemberEndpointHandlerData = {
    body: InviteOrganizationMemberRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/organizations/{id}/invite';
};

export type InviteOrganizationMemberEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type InviteOrganizationMemberEndpointHandlerError = InviteOrganizationMemberEndpointHandlerErrors[keyof InviteOrganizationMemberEndpointHandlerErrors];

export type InviteOrganizationMemberEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type InviteOrganizationMemberEndpointHandlerResponse = InviteOrganizationMemberEndpointHandlerResponses[keyof InviteOrganizationMemberEndpointHandlerResponses];

export type AcceptOrganizationInviteEndpointHandlerData = {
    body?: never;
    path: {
        inviteId: string;
    };
    query?: never;
    url: '/api/organizations/invites/{inviteId}/accept';
};

export type AcceptOrganizationInviteEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type AcceptOrganizationInviteEndpointHandlerError = AcceptOrganizationInviteEndpointHandlerErrors[keyof AcceptOrganizationInviteEndpointHandlerErrors];

export type AcceptOrganizationInviteEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type AcceptOrganizationInviteEndpointHandlerResponse = AcceptOrganizationInviteEndpointHandlerResponses[keyof AcceptOrganizationInviteEndpointHandlerResponses];

export type RejectOrganizationInviteEndpointHandlerData = {
    body?: never;
    path: {
        inviteId: string;
    };
    query?: never;
    url: '/api/organizations/invites/{inviteId}/reject';
};

export type RejectOrganizationInviteEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type RejectOrganizationInviteEndpointHandlerError = RejectOrganizationInviteEndpointHandlerErrors[keyof RejectOrganizationInviteEndpointHandlerErrors];

export type RejectOrganizationInviteEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type RejectOrganizationInviteEndpointHandlerResponse = RejectOrganizationInviteEndpointHandlerResponses[keyof RejectOrganizationInviteEndpointHandlerResponses];

export type CancelOrganizationInviteEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
        inviteId: string;
    };
    query?: never;
    url: '/api/organizations/{id}/invites/{inviteId}/cancel';
};

export type CancelOrganizationInviteEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type CancelOrganizationInviteEndpointHandlerError = CancelOrganizationInviteEndpointHandlerErrors[keyof CancelOrganizationInviteEndpointHandlerErrors];

export type CancelOrganizationInviteEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type CancelOrganizationInviteEndpointHandlerResponse = CancelOrganizationInviteEndpointHandlerResponses[keyof CancelOrganizationInviteEndpointHandlerResponses];

export type GetUserInvitesEndpointHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations/invites';
};

export type GetUserInvitesEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetUserInvitesEndpointHandlerError = GetUserInvitesEndpointHandlerErrors[keyof GetUserInvitesEndpointHandlerErrors];

export type GetUserInvitesEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfUserOrganizationInviteResponse;
};

export type GetUserInvitesEndpointHandlerResponse = GetUserInvitesEndpointHandlerResponses[keyof GetUserInvitesEndpointHandlerResponses];

export type TransferOrganizationOwnershipEndpointHandlerData = {
    body: TransferOrganizationOwnershipRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/organizations/{id}/transfer-ownership';
};

export type TransferOrganizationOwnershipEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type TransferOrganizationOwnershipEndpointHandlerError = TransferOrganizationOwnershipEndpointHandlerErrors[keyof TransferOrganizationOwnershipEndpointHandlerErrors];

export type TransferOrganizationOwnershipEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type TransferOrganizationOwnershipEndpointHandlerResponse = TransferOrganizationOwnershipEndpointHandlerResponses[keyof TransferOrganizationOwnershipEndpointHandlerResponses];

export type UpdateOrganizationMemberRoleEndpointHandlerData = {
    body: UpdateOrganizationMemberRoleRequest;
    path: {
        id: string;
        memberId: string;
    };
    query?: never;
    url: '/api/organizations/{id}/members/{memberId}/role';
};

export type UpdateOrganizationMemberRoleEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type UpdateOrganizationMemberRoleEndpointHandlerError = UpdateOrganizationMemberRoleEndpointHandlerErrors[keyof UpdateOrganizationMemberRoleEndpointHandlerErrors];

export type UpdateOrganizationMemberRoleEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type UpdateOrganizationMemberRoleEndpointHandlerResponse = UpdateOrganizationMemberRoleEndpointHandlerResponses[keyof UpdateOrganizationMemberRoleEndpointHandlerResponses];

export type GetOrganizationMembersEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/organizations/{id}/members';
};

export type GetOrganizationMembersEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetOrganizationMembersEndpointHandlerError = GetOrganizationMembersEndpointHandlerErrors[keyof GetOrganizationMembersEndpointHandlerErrors];

export type GetOrganizationMembersEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfOrganizationMemberResponse;
};

export type GetOrganizationMembersEndpointHandlerResponse = GetOrganizationMembersEndpointHandlerResponses[keyof GetOrganizationMembersEndpointHandlerResponses];

export type RemoveOrganizationMemberEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
        memberId: string;
    };
    query?: never;
    url: '/api/organizations/{id}/members/{memberId}';
};

export type RemoveOrganizationMemberEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type RemoveOrganizationMemberEndpointHandlerError = RemoveOrganizationMemberEndpointHandlerErrors[keyof RemoveOrganizationMemberEndpointHandlerErrors];

export type RemoveOrganizationMemberEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type RemoveOrganizationMemberEndpointHandlerResponse = RemoveOrganizationMemberEndpointHandlerResponses[keyof RemoveOrganizationMemberEndpointHandlerResponses];

export type GetSemestersEndpointHandlerData = {
    body?: never;
    path?: never;
    query: {
        organizationId: string;
    };
    url: '/api/semesters';
};

export type GetSemestersEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
};

export type GetSemestersEndpointHandlerError = GetSemestersEndpointHandlerErrors[keyof GetSemestersEndpointHandlerErrors];

export type GetSemestersEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfSemesterResponse;
};

export type GetSemestersEndpointHandlerResponse = GetSemestersEndpointHandlerResponses[keyof GetSemestersEndpointHandlerResponses];

export type CreateSemesterEndpointHandlerData = {
    body: CreateSemesterRequest;
    path?: never;
    query?: never;
    url: '/api/semesters';
};

export type CreateSemesterEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
};

export type CreateSemesterEndpointHandlerError = CreateSemesterEndpointHandlerErrors[keyof CreateSemesterEndpointHandlerErrors];

export type CreateSemesterEndpointHandlerResponses = {
    /**
     * Created
     */
    201: ApiResponseOfGuid;
};

export type CreateSemesterEndpointHandlerResponse = CreateSemesterEndpointHandlerResponses[keyof CreateSemesterEndpointHandlerResponses];

export type DeleteSemesterEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/semesters/{id}';
};

export type DeleteSemesterEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type DeleteSemesterEndpointHandlerError = DeleteSemesterEndpointHandlerErrors[keyof DeleteSemesterEndpointHandlerErrors];

export type DeleteSemesterEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type DeleteSemesterEndpointHandlerResponse = DeleteSemesterEndpointHandlerResponses[keyof DeleteSemesterEndpointHandlerResponses];

export type GetSemesterByIdEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/semesters/{id}';
};

export type GetSemesterByIdEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type GetSemesterByIdEndpointHandlerError = GetSemesterByIdEndpointHandlerErrors[keyof GetSemesterByIdEndpointHandlerErrors];

export type GetSemesterByIdEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfSemesterResponse;
};

export type GetSemesterByIdEndpointHandlerResponse = GetSemesterByIdEndpointHandlerResponses[keyof GetSemesterByIdEndpointHandlerResponses];

export type GetCurrentUserSessionsEndpointHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sessions/me';
};

export type GetCurrentUserSessionsEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetCurrentUserSessionsEndpointHandlerError = GetCurrentUserSessionsEndpointHandlerErrors[keyof GetCurrentUserSessionsEndpointHandlerErrors];

export type GetCurrentUserSessionsEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfSessionData;
};

export type GetCurrentUserSessionsEndpointHandlerResponse = GetCurrentUserSessionsEndpointHandlerResponses[keyof GetCurrentUserSessionsEndpointHandlerResponses];

export type RevokeCurrentUserSessionEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/sessions/{id}/revoke';
};

export type RevokeCurrentUserSessionEndpointHandlerErrors = {
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type RevokeCurrentUserSessionEndpointHandlerError = RevokeCurrentUserSessionEndpointHandlerErrors[keyof RevokeCurrentUserSessionEndpointHandlerErrors];

export type RevokeCurrentUserSessionEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type RevokeCurrentUserSessionEndpointHandlerResponse = RevokeCurrentUserSessionEndpointHandlerResponses[keyof RevokeCurrentUserSessionEndpointHandlerResponses];

export type RevokeAllCurrentUserSessionsEndpointHandlerData = {
    body?: never;
    path?: never;
    query?: {
        keepCurrentUserSession?: boolean;
    };
    url: '/api/sessions/revoke-all';
};

export type RevokeAllCurrentUserSessionsEndpointHandlerErrors = {
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type RevokeAllCurrentUserSessionsEndpointHandlerError = RevokeAllCurrentUserSessionsEndpointHandlerErrors[keyof RevokeAllCurrentUserSessionsEndpointHandlerErrors];

export type RevokeAllCurrentUserSessionsEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type RevokeAllCurrentUserSessionsEndpointHandlerResponse = RevokeAllCurrentUserSessionsEndpointHandlerResponses[keyof RevokeAllCurrentUserSessionsEndpointHandlerResponses];

export type CreateTermEndpointHandlerData = {
    body: CreateTermRequest;
    path?: never;
    query?: never;
    url: '/api/terms';
};

export type CreateTermEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
};

export type CreateTermEndpointHandlerError = CreateTermEndpointHandlerErrors[keyof CreateTermEndpointHandlerErrors];

export type CreateTermEndpointHandlerResponses = {
    /**
     * Created
     */
    201: ApiResponseOfGuid;
};

export type CreateTermEndpointHandlerResponse = CreateTermEndpointHandlerResponses[keyof CreateTermEndpointHandlerResponses];

export type GetTermsBySemesterEndpointHandlerData = {
    body?: never;
    path: {
        semesterId: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/terms/semester/{semesterId}';
};

export type GetTermsBySemesterEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type GetTermsBySemesterEndpointHandlerError = GetTermsBySemesterEndpointHandlerErrors[keyof GetTermsBySemesterEndpointHandlerErrors];

export type GetTermsBySemesterEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfIReadOnlyListOfTermResponse;
};

export type GetTermsBySemesterEndpointHandlerResponse = GetTermsBySemesterEndpointHandlerResponses[keyof GetTermsBySemesterEndpointHandlerResponses];

export type DeleteTermEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/terms/{id}';
};

export type DeleteTermEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type DeleteTermEndpointHandlerError = DeleteTermEndpointHandlerErrors[keyof DeleteTermEndpointHandlerErrors];

export type DeleteTermEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type DeleteTermEndpointHandlerResponse = DeleteTermEndpointHandlerResponses[keyof DeleteTermEndpointHandlerResponses];

export type GetTermByIdEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        organizationId: string;
    };
    url: '/api/terms/{id}';
};

export type GetTermByIdEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
};

export type GetTermByIdEndpointHandlerError = GetTermByIdEndpointHandlerErrors[keyof GetTermByIdEndpointHandlerErrors];

export type GetTermByIdEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfTermResponse;
};

export type GetTermByIdEndpointHandlerResponse = GetTermByIdEndpointHandlerResponses[keyof GetTermByIdEndpointHandlerResponses];

export type GetUsersEndpointHandlerData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number | string;
        id?: string;
        userName?: string;
    };
    url: '/api/users';
};

export type GetUsersEndpointHandlerErrors = {
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetUsersEndpointHandlerError = GetUsersEndpointHandlerErrors[keyof GetUsersEndpointHandlerErrors];

export type GetUsersEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfCursorPageOfUserResponse;
};

export type GetUsersEndpointHandlerResponse = GetUsersEndpointHandlerResponses[keyof GetUsersEndpointHandlerResponses];

export type GetCurrentUserEndpointHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetCurrentUserEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetCurrentUserEndpointHandlerError = GetCurrentUserEndpointHandlerErrors[keyof GetCurrentUserEndpointHandlerErrors];

export type GetCurrentUserEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfUserResponse;
};

export type GetCurrentUserEndpointHandlerResponse = GetCurrentUserEndpointHandlerResponses[keyof GetCurrentUserEndpointHandlerResponses];

export type UpdateCurrentUserEndpointHandlerData = {
    body: UpdateCurrentUserRequest;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UpdateCurrentUserEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type UpdateCurrentUserEndpointHandlerError = UpdateCurrentUserEndpointHandlerErrors[keyof UpdateCurrentUserEndpointHandlerErrors];

export type UpdateCurrentUserEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type UpdateCurrentUserEndpointHandlerResponse = UpdateCurrentUserEndpointHandlerResponses[keyof UpdateCurrentUserEndpointHandlerResponses];

export type GetUserByIdEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserByIdEndpointHandlerErrors = {
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type GetUserByIdEndpointHandlerError = GetUserByIdEndpointHandlerErrors[keyof GetUserByIdEndpointHandlerErrors];

export type GetUserByIdEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfUserResponse;
};

export type GetUserByIdEndpointHandlerResponse = GetUserByIdEndpointHandlerResponses[keyof GetUserByIdEndpointHandlerResponses];

export type UpdateCurrentUserPasswordEndpointHandlerData = {
    body: UpdateCurrentUserPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/password';
};

export type UpdateCurrentUserPasswordEndpointHandlerErrors = {
    /**
     * Bad Request
     */
    400: ApiResponseOfObject;
    /**
     * Unauthorized
     */
    401: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type UpdateCurrentUserPasswordEndpointHandlerError = UpdateCurrentUserPasswordEndpointHandlerErrors[keyof UpdateCurrentUserPasswordEndpointHandlerErrors];

export type UpdateCurrentUserPasswordEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type UpdateCurrentUserPasswordEndpointHandlerResponse = UpdateCurrentUserPasswordEndpointHandlerResponses[keyof UpdateCurrentUserPasswordEndpointHandlerResponses];

export type PromoteUserEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/promote';
};

export type PromoteUserEndpointHandlerErrors = {
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type PromoteUserEndpointHandlerError = PromoteUserEndpointHandlerErrors[keyof PromoteUserEndpointHandlerErrors];

export type PromoteUserEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type PromoteUserEndpointHandlerResponse = PromoteUserEndpointHandlerResponses[keyof PromoteUserEndpointHandlerResponses];

export type DemoteUserEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/demote';
};

export type DemoteUserEndpointHandlerErrors = {
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Conflict
     */
    409: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type DemoteUserEndpointHandlerError = DemoteUserEndpointHandlerErrors[keyof DemoteUserEndpointHandlerErrors];

export type DemoteUserEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type DemoteUserEndpointHandlerResponse = DemoteUserEndpointHandlerResponses[keyof DemoteUserEndpointHandlerResponses];

export type LockUserEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/lock';
};

export type LockUserEndpointHandlerErrors = {
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type LockUserEndpointHandlerError = LockUserEndpointHandlerErrors[keyof LockUserEndpointHandlerErrors];

export type LockUserEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type LockUserEndpointHandlerResponse = LockUserEndpointHandlerResponses[keyof LockUserEndpointHandlerResponses];

export type UnlockUserEndpointHandlerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/unlock';
};

export type UnlockUserEndpointHandlerErrors = {
    /**
     * Forbidden
     */
    403: ApiResponseOfObject;
    /**
     * Not Found
     */
    404: ApiResponseOfObject;
    /**
     * Internal Server Error
     */
    500: ApiResponseOfObject;
};

export type UnlockUserEndpointHandlerError = UnlockUserEndpointHandlerErrors[keyof UnlockUserEndpointHandlerErrors];

export type UnlockUserEndpointHandlerResponses = {
    /**
     * OK
     */
    200: ApiResponseOfObject;
};

export type UnlockUserEndpointHandlerResponse = UnlockUserEndpointHandlerResponses[keyof UnlockUserEndpointHandlerResponses];
