<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="FluentValidation" Version="8.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.12.41" />
    <PackageVersion Include="Scrutor" Version="7.0.0" />
    <PackageVersion Include="StackExchange.Redis" Version="2.11.0" />
  </ItemGroup>

</Project>
