import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // dist is build output; src/api is generated by openapi-ts (npm run openapi-ts)
  // and must not be linted by hand — it is overwritten on every regeneration.
  globalIgnores(['dist', 'src/api']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // Every dashboard page fetches its data in a mount effect
      // (useEffect -> async fetch -> setState). That is idiomatic data
      // fetching, not a cascading render: the setState happens
      // asynchronously after the network round-trip, so there is no
      // render -> effect -> render loop. The rule cannot tell async
      // fetching apart from synchronous setState-in-effect, so it flags
      // all of them. Direct sync setState in effects is still reviewed
      // in code review; refs misuse is still covered by react-hooks/refs.
      'react-hooks/set-state-in-effect': 'off',
    },
  },
])
