// <auto-generated />
using System;
using EduTracker.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduTracker.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408190119_AcademicPeopleAndClasses")]
    partial class AcademicPeopleAndClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.AcademicClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_organization_id_code");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_organization_id_code");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.CourseOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.HasKey("Id")
                        .HasName("pk_course_offerings");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_offerings_course_id");

                    b.HasIndex("TermId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_course_offerings_term_id_course_id");

                    b.ToTable("course_offerings", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("pk_semesters");

                    b.HasIndex("OrganizationId", "StartYear")
                        .IsUnique()
                        .HasDatabaseName("ix_semesters_organization_id_start_year");

                    b.ToTable("semesters", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OrganizationMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_member_id");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("student_number");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_students_class_id");

                    b.HasIndex("OrganizationMemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_organization_member_id");

                    b.HasIndex("OrganizationId", "StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_students_organization_id_student_number");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OrganizationMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_member_id");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("staff_id");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.HasIndex("OrganizationMemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_organization_member_id");

                    b.HasIndex("OrganizationId", "StaffId")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_organization_id_staff_id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.HasKey("Id")
                        .HasName("pk_terms");

                    b.HasIndex("SemesterId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_terms_semester_id_ordinal");

                    b.ToTable("terms", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_organizations_name");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_organizations_owner_user_id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.OrganizationInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_organization_invites");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_organization_invites_invited_by_user_id");

                    b.HasIndex("InvitedUserId", "Status")
                        .HasDatabaseName("ix_organization_invites_invited_user_id_status");

                    b.HasIndex("OrganizationId", "InvitedUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_invites_organization_id_invited_user_id")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_organization_invites_organization_id_status");

                    b.ToTable("organization_invites", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_members");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_members_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_members_user_id");

                    b.HasIndex("OrganizationId", "Role")
                        .HasDatabaseName("ix_organization_members_organization_id_role");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_organization_members_organization_id_status");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_members_organization_id_user_id");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_hash");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmailHash")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_hash");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("boolean")
                        .HasColumnName("remember_me");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("ix_user_sessions_user_id_is_revoked");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.AcademicClass", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_organizations_organization_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("AcademicClassId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("AcademicClassId");

                            b1.ToTable("classes");

                            b1.WithOwner()
                                .HasForeignKey("AcademicClassId")
                                .HasConstraintName("fk_classes_classes_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Course", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_organizations_organization_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("CourseId");

                            b1.ToTable("courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId")
                                .HasConstraintName("fk_courses_courses_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.CourseOffering", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Academics.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_offerings_courses_course_id");

                    b.HasOne("EduTracker.Domain.Entities.Academics.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_offerings_terms_term_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("CourseOfferingId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("CourseOfferingId");

                            b1.ToTable("course_offerings");

                            b1.WithOwner()
                                .HasForeignKey("CourseOfferingId")
                                .HasConstraintName("fk_course_offerings_course_offerings_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Semester", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_semesters_organizations_organization_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("SemesterId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("SemesterId");

                            b1.ToTable("semesters");

                            b1.WithOwner()
                                .HasForeignKey("SemesterId")
                                .HasConstraintName("fk_semesters_semesters_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Student", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Academics.AcademicClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_students_classes_class_id");

                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_organizations_organization_id");

                    b.HasOne("EduTracker.Domain.Entities.Organizations.OrganizationMember", "OrganizationMember")
                        .WithMany()
                        .HasForeignKey("OrganizationMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_organization_members_organization_member_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("StudentId");

                            b1.ToTable("students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId")
                                .HasConstraintName("fk_students_students_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationMember");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Teacher", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_organizations_organization_id");

                    b.HasOne("EduTracker.Domain.Entities.Organizations.OrganizationMember", "OrganizationMember")
                        .WithMany()
                        .HasForeignKey("OrganizationMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_organization_members_organization_member_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("TeacherId");

                            b1.ToTable("teachers");

                            b1.WithOwner()
                                .HasForeignKey("TeacherId")
                                .HasConstraintName("fk_teachers_teachers_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("OrganizationMember");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Academics.Term", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Academics.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_terms_semesters_semester_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("TermId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("TermId");

                            b1.ToTable("terms");

                            b1.WithOwner()
                                .HasForeignKey("TermId")
                                .HasConstraintName("fk_terms_terms_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.Organization", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Users.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_users_owner_user_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId")
                                .HasConstraintName("fk_organizations_organizations_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.OrganizationInvite", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Users.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_invites_users_invited_by_user_id");

                    b.HasOne("EduTracker.Domain.Entities.Users.User", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_invites_users_invited_user_id");

                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_invites_organizations_organization_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("OrganizationInviteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("OrganizationInviteId");

                            b1.ToTable("organization_invites");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationInviteId")
                                .HasConstraintName("fk_organization_invites_organization_invites_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.OrganizationMember", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organizations_organization_id");

                    b.HasOne("EduTracker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_users_user_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("OrganizationMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("OrganizationMemberId");

                            b1.ToTable("organization_members");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationMemberId")
                                .HasConstraintName("fk_organization_members_organization_members_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Users.User", b =>
                {
                    b.OwnsOne("EduTracker.Domain.Components.Security.SensitiveDataState<EduTracker.Domain.Entities.Users.UserSensitive>", "SensitiveDataState", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<byte[]>("EncryptedData")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("encrypted_data");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("SensitiveDataState")
                        .IsRequired();
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Users.UserSession", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("UserSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("UserSessionId");

                            b1.ToTable("user_sessions");

                            b1.WithOwner()
                                .HasForeignKey("UserSessionId")
                                .HasConstraintName("fk_user_sessions_user_sessions_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
