// <auto-generated />
using System;
using EduTracker.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduTracker.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316115242_AddOrgInvitesDropNameUnique")]
    partial class AddOrgInvitesDropNameUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_organizations_name");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_organizations_owner_user_id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.OrganizationInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_organization_invites");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_organization_invites_invited_by_user_id");

                    b.HasIndex("InvitedUserId", "Status")
                        .HasDatabaseName("ix_organization_invites_invited_user_id_status");

                    b.HasIndex("OrganizationId", "InvitedUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_invites_organization_id_invited_user_id")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_organization_invites_organization_id_status");

                    b.ToTable("organization_invites", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_members");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_members_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_members_user_id");

                    b.HasIndex("OrganizationId", "Role")
                        .HasDatabaseName("ix_organization_members_organization_id_role");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_organization_members_organization_id_status");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_members_organization_id_user_id");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_hash");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmailHash")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_hash");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("boolean")
                        .HasColumnName("remember_me");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("ix_user_sessions_user_id_is_revoked");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.Organization", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Users.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_users_owner_user_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId")
                                .HasConstraintName("fk_organizations_organizations_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.OrganizationInvite", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Users.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_invites_users_invited_by_user_id");

                    b.HasOne("EduTracker.Domain.Entities.Users.User", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_invites_users_invited_user_id");

                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_invites_organizations_organization_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("OrganizationInviteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("OrganizationInviteId");

                            b1.ToTable("organization_invites");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationInviteId")
                                .HasConstraintName("fk_organization_invites_organization_invites_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Organizations.OrganizationMember", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organizations_organization_id");

                    b.HasOne("EduTracker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_users_user_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("OrganizationMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("OrganizationMemberId");

                            b1.ToTable("organization_members");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationMemberId")
                                .HasConstraintName("fk_organization_members_organization_members_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Users.User", b =>
                {
                    b.OwnsOne("EduTracker.Domain.Components.Security.SensitiveDataState<EduTracker.Domain.Entities.Users.UserSensitive>", "SensitiveDataState", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<byte[]>("EncryptedData")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("encrypted_data");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("SensitiveDataState")
                        .IsRequired();
                });

            modelBuilder.Entity("EduTracker.Domain.Entities.Users.UserSession", b =>
                {
                    b.HasOne("EduTracker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.OwnsOne("EduTracker.Domain.Components.Auditing.AuditState", "AuditState", b1 =>
                        {
                            b1.Property<Guid>("UserSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("UserSessionId");

                            b1.ToTable("user_sessions");

                            b1.WithOwner()
                                .HasForeignKey("UserSessionId")
                                .HasConstraintName("fk_user_sessions_user_sessions_id");
                        });

                    b.Navigation("AuditState")
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
