<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduTracker.Application\EduTracker.Application.csproj" />
    <ProjectReference Include="..\EduTracker.Domain\EduTracker.Domain.csproj" />
    <ProjectReference Include="..\EduTracker.Shared\EduTracker.Shared.csproj" />
  </ItemGroup>

</Project>
