// ─── Frontend-first seam for roster + attendance ────────────────────────────
// The backend slices for Enrollments (Build 01) and Attendance (Build 02) do
// not exist yet, so these pages develop against mock data. The shapes below
// deliberately mirror the contracts in FEATURE-ROADMAP.md:
//
//   GetClassRoster          -> RosterEntry[]
//   MarkClassAttendance     -> { sessionDate, entries: RegisterEntryInput[] }
//   Attendance summary math -> present+late over present+late+absent,
//                              excused excluded from the denominator.
//
// When the backend lands, swapping to the generated SDK should be a one-file
// change here. Do NOT import from api/sdk.gen.ts in this file: it is
// regenerated by `npm run openapi-ts` and any hand edits are discarded.

export type AttendanceStatus = "Present" | "Absent" | "Late" | "Excused";

export const ATTENDANCE_STATUSES: AttendanceStatus[] = [
    "Present",
    "Absent",
    "Late",
    "Excused",
];

export interface RosterEntry {
    id: string;
    studentId: string;
    firstName: string;
    lastName: string;
    enrolledAt: string; // ISO date
}

export interface RegisterEntryInput {
    studentId: string;
    status: AttendanceStatus;
    note: string | null;
}

export interface RegisterResult {
    sessionDate: string; // yyyy-mm-dd
    saved: number;
    savedAt: string; // ISO timestamp
}

export function fullName(entry: Pick<RosterEntry, "firstName" | "lastName">): string {
    return `${entry.firstName} ${entry.lastName}`;
}

export function getMockRoster(): RosterEntry[] {
    return [
        { id: "1", studentId: "1", firstName: "Alice", lastName: "Johnson", enrolledAt: "2026-04-01" },
        { id: "2", studentId: "2", firstName: "Bob", lastName: "Smith", enrolledAt: "2026-04-02" },
    ];
}

// Stand-in for POST .../attendance. Resolves after a short delay so the UI
// can exercise its saving / saved / dirty states before real HTTP exists.
export function submitMockRegister(
    sessionDate: string,
    entries: RegisterEntryInput[],
): Promise<RegisterResult> {
    return new Promise((resolve) => {
        window.setTimeout(() => {
            resolve({
                sessionDate,
                saved: entries.length,
                savedAt: new Date().toISOString(),
            });
        }, 600);
    });
}

export interface AttendanceTally {
    present: number;
    absent: number;
    late: number;
    excused: number;
    counted: number;
    rate: number; // 0..1, excused excluded from the denominator
}

export function tallyRegister(statuses: AttendanceStatus[]): AttendanceTally {
    const present = statuses.filter((s) => s === "Present").length;
    const absent = statuses.filter((s) => s === "Absent").length;
    const late = statuses.filter((s) => s === "Late").length;
    const excused = statuses.filter((s) => s === "Excused").length;
    const counted = present + late + absent;
    return {
        present,
        absent,
        late,
        excused,
        counted,
        rate: counted === 0 ? 0 : (present + late) / counted,
    };
}
